# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave.xci
# IP: The module: 'Sine_wave' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sine_wave'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave.xci
# IP: The module: 'Sine_wave' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sine_wave'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
