#! /bin/sh
export PATH || exec /bin/sh "$0" $argv
# Get the path to this exec
xinfoloc=`dirname "$0"`

unset LANG
platform=`uname -s`
	
# run xinfo executable depending on different platform
if [ "$platform" = "Linux" ]
then
    machineType=`uname -m`;	# Get the machine type
    if [ "$machineType" = "x86_64" ]
    then
	# 64 bit
        if [ -f "$xinfoloc/bin/lin64/xinfoenv" ]
        then
            "$xinfoloc/bin/lin64/xinfoenv" $*
        elif [ -f "$xinfoloc/bin/lin/xinfoenv" ]
        then
            "$xinfoloc/bin/lin/xinfoenv" $*
        else
            echo "Product is not supported on \"$platform $machineType\" platform."
        fi
    else
        if [ -f "$xinfoloc/bin/lin/xinfoenv" ]
        then
            "$xinfoloc/bin/lin/xinfoenv" $*
        else
            echo "Product is not supported on \"$platform $machineType\" platform."
        fi
    fi
else
	echo "Un-supported platform: $platform"
fi

