# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.cache/wt [current_project]
set_property parent.project_path C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave.xci
set_property is_locked true [get_files c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Sine_wave -part xc7z010clg400-1 -mode out_of_context

rename_ref -prefix_all Sine_wave_

write_checkpoint -force -noxdef Sine_wave.dcp

catch { report_utilization -file Sine_wave_utilization_synth.rpt -pb Sine_wave_utilization_synth.pb }

if { [catch {
  file copy -force C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.runs/Sine_wave_synth_1/Sine_wave.dcp c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.ip_user_files/ip/Sine_wave]} {
  catch { 
    file copy -force c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_stub.v C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.ip_user_files/ip/Sine_wave
  }
}

if {[file isdir C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.ip_user_files/ip/Sine_wave]} {
  catch { 
    file copy -force c:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.srcs/sources_1/ip/Sine_wave/Sine_wave_stub.vhdl C:/Users/RazBB/Desktop/RP_FPGA/RP_out_mix/RP_out_mix.ip_user_files/ip/Sine_wave
  }
}
